# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'route' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for route
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'routeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'routeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
